export const recipeData = [
  {
    id: '1',
    name: 'Pilaf',
    category: 'Beef',
    imageUrl: '/images/plovas.jpg',
    ingredients: [
      '500 g Beef',
      '1 onion',
      '2-3 carrots',
      '1/2 t.s.p. salt',
      '1/4 t.s.p. pepper',
      'Bay leaf',
      '1 t.s.p garlic powder',
      '1 t.s.p paprika',
      '1/2 t.s.p kumin',
      '700 ml beef broth',
      '2 t.s.p tomato paste',
      '350 g rice',
      '1 garlic head',
      'Fresh parsley',
    ],
    instructions: [
      'Cut beef in small cubic pieces.',
      'Cut onion and carrot into small stripes.',
      'Heat the oil in the pan, cook onions for few minutes.',
      'Add carrots, cook for few minutes.',
      'Cook beef but not until it gets roasted.',
      'Mix all the spices and put into the pot.',
      'Add the broth, bay leaf and mix everything.',
      'Cook on low heat for 2-3 hours.',
      'Clean the rice and add to the pot for 20-30 minutes.',
      'Add the cut garlic head.',
      'Serve with fresh parsley.',
    ],
  },
  {
    id: '2',
    name: 'Chicken Noodles',
    category: 'Chicken',
    imageUrl: '/images/stir-fry.jpg',
    ingredients: [
      '200 g noodles',
      'Oil to fry',
      '400 g of chicken',
      '3 garlic cloves',
      '1 red paprika',
      '200 g beans or brocolli',
      '100 g shiitake mushrooms',
      'Sesame seeds',
    ],
    sauce: [
      '4 tbsp soy sauce',
      '2 tbsp oyster sauce',
      '2 tbsp sweet chilli sauce',
      '2 tbsp water',
      '1 tbsp sugar or honey',
      '1 tbsp rice vinegar',
      '1 tbsp sesame oil',
    ],
    instructions: [
      'Cook the noodles as instructed.',
      'Mix everything in a bowl for the sauce.',
      'Preheat the oven and cook the chicken.',
      'Add garlic, ginger and cook for a minute.',
      'Add the cooked noodles and mix it.',
      'Serve with sesame seeds.',
    ],
  },
  {
    id: '3',
    name: 'Creamy Lemon White Fish',
    category: 'Fish',
    imageUrl: '/images/creamyFish.webp',
    ingredients: [
      '2 tea spoons butter',
      '2 white fish fillet',
      '250 ml cream (20%)',
      '1 lemon',
      'Salt and pepper',
    ],

    instructions: [
      'Preheat the pan and add butter.',
      'Fry fish from both sides until golden and season with salt and pepper.',
      'Cut half a lemon in slices.',
      'Add cream to the fish.',
      'Add the lemon slices and squeze the remaining half of the lemon.',
      'Cook fish in sauce for 5-10 minutes until cream thickens.',
      'Serve with mashed potatoes or rice.',
    ],
  },
  {
    id: '4',
    name: 'Pulled Chicken Quesadilla',
    category: 'Chicken',
    imageUrl: '/images/quesadilla.jpg',
    ingredients: [
      '2 chicken breasts',
      '1 tabl. sp. olive oi',
      'Taco spices pack',
      '2 tabl. sp. salsa sauce',
      '2 tabl. sp. cream cheese',
      '100 g cheddar cheese',
      '6 tortillas',
      'Coriander',
      'Jelapenos',
    ],
    sauce: ['2 Avocados', 'Lime juice', 'Salt and Pepper', '1 tomato'],
    instructions: [
      'Mix the chicken with oil and a mixture of spices.',
      'Fry the chicken: Put the chicken in the pan, fry it on high heat for 3 minutes on each side, then reduce the heat to minimum, cover the pan and fry for another 15 minutes. Let the fried chicken stand at room temperature for 5 minutes, then tear it into thin strips with the help of two forks.',
      'Mix the shredded chicken with salsa sauce and cream cheese.',
      'Grate the cheddar cheese.',
      'Place the chicken filling on the tortilla, add cheese and cover with another tortilla.',
      'Heat oil in a pan and add the tortilla to fry. Fry on medium heat for 3-4 minutes, sometimes pressing the tortilla with your hands or a spatula so that it browns evenly. Carefully turn the tortilla over and cook for another 3-4 minutes. Once cooked, we cut it into 4 or 6 parts.',
      'Prepare guacamole: put avocados in a bowl, squeeze lime juice, grate garlic, add salt and pepper, mash with a fork until smooth. Then we mix in the tomato cubes.',
      'Serve quesadillas with guacamole, lime, chili slices and fresh coriander.',
    ],
  },
  {
    id: '5',
    name: 'Mashed Pumpkin Soup',
    category: 'Soup',
    imageUrl: '/images/pumpkinSoup.webp',
    ingredients: [
      '1 pumpkin',
      '2-3 carrots',
      '2 potatoes',
      '1 onion',
      '1 vegetable broth cube',
      '250 ml 7% cream',
      '500 ml water',
      'Pumpkin seads for serving',
      'Grated cheese for serving',
    ],
    instructions: [
      'Peel pumpkin, potatoes carrots and onion. Cut in big pieces',
      'Boil pumpkin, potatoes carrots and onion together in a big pot for 20-25 minutes.',
      'In 500 ml of hot water dissolve vegetable cube. Set aside.',
      'When vegetables are soft, remove the water from the pot, add vegetable broth. Use blender until everything is mashed. Check for salt and add more if necessary',
      'Add 250 ml of cream, mix well. Add freshly ground black pepper',
      'Serve with pumpkin seads and / or grated cheese',
    ],
  },
  {
    id: '6',
    name: 'Creamy Chicken Breast In Spinach Parmesan Sauce',
    category: 'Chicken',
    imageUrl: '/images/chickenParmesan.jpg',
    ingredients: [
      '2-3 chicken breasts',
      '2 tab. sp. butter',
      'Salt and Pepper',
      '1 tea sp. oregano',
      '1 minced onion',
      '4 miced cloves garlic',
      'Half a jar sundried tomatoes',
      '1,5 cup chicken broth',
      '250 ml cream',
      '1/3 cup grated parmesan',
      '1 cup spinach',
    ],

    instructions: [
      'Season chicken breasts with salt pepper and oregano',
      'Cook chicken for 4 mins on each side until brown',
      'Transfer chicken breast to a plate and set aside',
      'Add butter to the same pan and cook onion, garlic, sundried tomatoes',
      'Add chicken broth, cream and parmesan cheese and simmer for 2-3 mins',
      'Add spinach to the mixture',
      'Add chicken breasts back to the pan and cook 2-3 mins',
    ],
  },
  {
    id: '7',
    name: 'Beef Teryaki',
    category: 'Beef',
    imageUrl: '/images/beefTeryaki.jpg',
    ingredients: [
      '500 g beef',
      '1 cup of rice',
      '2-3 carrots',
      '1 broccoli',
      '1 paprika',
      'Sesame seeds',
      'Spring onion',
    ],
    sauce: [
      '1/4 cup soy sauce',
      '1/2 cup water',
      '1/4 cup brown sugar',
      '2 teaspoons minced garlic',
      '2 teaspoons minced ginger',
      '1 tablespoon of honey',
      '1 teaspoon toasted sesame oil',
      '1 tablespoon + 1 teaspoon cornstarch',
    ],
    instructions: [
      'Fry the beef with sesame oil',
      'Add garlic to the pan',
      'Add vegetables',
      'Put all the sauce ingredients in a small pot and heat it until thickens',
      'Add the sauce to the pan',
      'Serve with rice and spring onion and sesame seeds',
    ],
  },
  {
    id: '8',
    name: 'Thai Soup',
    category: 'Soup',
    imageUrl: '/images/thaiSoup.jpg',
    ingredients: [
      '10-15 shrimps',
      '2 garlic cloves',
      '2 cm ginger',
      '1 tabl. sp. red curry paste',
      '400 ml coconut milk',
      '500 ml chicken broth',
      'Pack of shiitake mushrooms',
      '100 g rice vermicelli',
      'Lemon juice',
      'Chilli pepper',
      'Sesame seeds',
      'Fresh Coriander',
    ],

    instructions: [
      'Fry the shrimps for few minutes',
      'Add garlic, ginger, red curry paste and fry few more minutes',
      'Boil the broth, add mushrooms and everything that was in a pan',
      'After few minutes add vermicelli and boil for few minutes',
      'Add coconut milk, squeeze lemon',
      'Taste, add salt n pepper if needed',
      'Serve with coriander, chilli and sesame seeds',
    ],
  },
  {
    id: '9',
    name: 'Chicken BBQ Wings',
    category: 'Chicken',
    imageUrl: '/images/chickenBBQ.jpg',
    ingredients: [
      '10 Chicken Wings',
      '1 cup of flour',
      '1 teaspoon salt',
      '1 teaspoon pepper',
      '1 teaspoon paprika',
      '1 teaspoon garlic powder',
      '1 cup BBQ sauce',
      '1/2 cup honey',
      '1 teaspoon sriracha sauce',
    ],
    sauce: [
      'Few spoons of greek yoghurt',
      'Fresh coriander',
      'Fresh lemon to squeeze',
      'Salt and pepper',
    ],

    instructions: [
      'Preheat oven to 220 C',
      'In a bowl, combine flour, chili powder, salt, pepper, paprika, and garlic powder. Coat the wings in the flour evenly, shaking off any excess.',
      'Place the floured wings on a parchment paper–lined baking sheet and spread them out in a single layer.',
      'Bake for 45 minutes, flipping halfway through, until skin is crispy and golden brown.',
      'In a separate bowl, combine the BBQ sauce, honey and sriracha. Stir the cooked wings in the sauce and coat them evenly.',
      'Place the coated wings back onto the baking sheet and spread them in a single layer.',
      'Bake for 8 to 10 minutes, until sauce is bubbly and caramelized.',
      'Mix the sauce ingredients.',
      'Serve with french fries and/or sliced carrots and the sauce',
    ],
  },
  {
    id: '10',
    name: 'Hangover Salad By Ema',
    category: 'Salad',
    imageUrl: '/images/pachmelSalad.jpg',
    ingredients: [
      'Iceberg Salad',
      '1 boiled egg',
      'Serrano ham',
      '1 Avocado',
      'Cherry tomaotes',
      'Croutons',
      'Balsamico creme',
      'Parmesan cheese',
    ],

    instructions: [
      'Combine all the ingredients nicely in a plate.',
      'Grate parmesan cheese on top.',
      'Add balsamico creme and olive oil.',
    ],
  },
  {
    id: '11',
    name: 'Chickpea Tuna Salad',
    category: 'Salad',
    imageUrl: '/images/chickpeaSalad.jpg',
    ingredients: [
      '1 can drained chickpeas',
      'Celary',
      '1 red onion',
      '1 can of tuna',
    ],
    sauce: [
      '2 table spoons mayonaise',
      '1 table spoon Dijon mustard',
      '2 table spoons olive oil',
      '1 squezed lemon juice',
      'Salt and Pepper',
    ],
    instructions: [
      'Whisk to combine sauce ingredients.',
      'Add to a bowl chickpeas, chopped onion and celary.',
      'Add tuna and dressing. Stir to combine.',
    ],
  },
  {
    id: '12',
    name: 'Beef Stroganoff',
    category: 'Beef',
    imageUrl: '/images/beefStroganov.jpg',
    ingredients: [
      '500 g beef',
      '400 g mushrooms',
      '2 teaspoons butter',
      '250 ml cream',
      '1 onions',
      '2 cloves of garlic',
      '1 tea spoon tomato paste',
      'Dill',
    ],

    instructions: [
      'Cut beef in cubes.',
      'Cook mushrooms, onion and garlic in butter.',
      'Cook beef until brown.',
      'Add salt and pepper.',
      'Add cream and a spoon of tomato paste. Wait until the sauce thickens',
      'Serve with mashed potatoes and dill.',
    ],
  },
  {
    id: '13',
    name: 'Chicken Soy Wings',
    category: 'Chicken',
    imageUrl: '/images/chickenSoya.jpg',
    ingredients: [
      '1 kg chicken wings',
      '1/2 cup soy sauce',
      '2 cups water',
      '2 cm ginger',
      '2-3 star anise',
      '2 teaspoons garlic powder',
      'Sesame seeds',
      '1 ciabatta',
      'Spring Onion',
    ],

    instructions: [
      'Combine everything in the boiling pot.',
      'Cook until chicken is done (Approx. 45 minutes)',
      'Remove the chicken.',
      'Reduce liquid until thick and sticky like honey',
      'Add chicken into the sauce and mix.',
      'Serve with spring onions sesame seeds and ciabatta.',
    ],
  },
  {
    id: '14',
    name: 'Creamy Shrimps Pasta',
    category: 'Fish',
    imageUrl: '/images/shrimpPasta.jpg',
    ingredients: [
      'Spaghetti to boil',
      'Shrimps',
      '250 ml of cream',
      '1 teaspoon paprika powder',
      '1 teaspoon garlic powder',
      'Grated cheese',
      '1 table spoon philadelphia cream',
      'Grated lemon zeist',
      'Salt and Pepper',
      'Fresh Parsley',
    ],

    instructions: [
      'Cook the pasta.',
      'Preheat the pan with oil',
      'Add shirmps, season with paprika and garlic and cook for a minute from each side.',
      'Remove the shrimps from the pan.',
      'In the same pan add cream, cheese and a half a cup of boiled pasta water.',
      'Taste it, add salt and pepper if needed',
      'Add the lemon zeist and the shrimps.',
      'Serve with fresh parsley.',
    ],
  },
  {
    id: '15',
    name: 'Chicken Thai Curry',
    category: 'Chicken',
    imageUrl: '/images/thaicurry.jpg',
    ingredients: [
      '1 table spoon coconut oil',
      '2-3 cm ginger',
      '3 cloves of garlic',
      '1 lime',
      '5 tea spoons red curry paste',
      '400 ml coconut milk',
      '1 cup chicken broth',
      '1 table spoon oyster sauce',
      '1 table spoon brown sugar',
      '500 g chicken breast',
      'Paprika | Beans | Brocolli | Carrots',
      'Fresh koriander to serve',
      'Fresh basil to serve',
    ],

    instructions: [
      'Heat oil in a pan/pot, grate ginger, garlic, lime peel and fry for 2 minutes.',
      'Add the curry paste and heat for another minute.',
      'Add coconut milk, chicken broth, oyster sauce, and brown sugar. Mix everything well to make a uniform sauce.',
      'As the sauce boils, add the chicken cut into strips and cook on medium heat for about 20 minutes - until the chicken is cooked.',
      'Add the vegetables and cook for a few more minutes.',
      'Serve with fresh coriander, basil and rice.',
    ],
  },
  {
    id: '16',
    name: 'Kotletukai',
    category: 'Beef',
    imageUrl: '/images/meatballs.jpg',
    ingredients: [
      '700 g minced beef',
      '1/2 tablespoon salt',
      '1/4 tablespoon pepper',
      '1 teaspoon garlic powder',
      '1/2 teaspoon paprika powder',
      '1/2 cup panko breadcrumbs',
      '1 egg',
      'Olive oil to cook',
    ],
    sauce: [
      '1 tablespoon olive oil to cook',
      '1 onion',
      '400 g mushrooms',
      '2 tablespoons of flour',
      '200 ml cream',
      '300 ml beef broth',
      '1 teaspoon Dijon mustard',
      '2 tablespoons soy sauce',
      'Parsley to serve',
    ],
    instructions: [
      'Mix the minced beef with spices, panko breadcrumbs and egg. Form small balls',
      'Preheat the pan with oil and cook the kotlets from both sides until brown. They must not touch each other. Take the cooked ones out of the pan',
      'Preheat the pan with oil and add onion. Mix and cook until golden. Add mushrooms, mix until cooked',
      'Add flour and mix well. Then add broth until the sauce thickens. Lastly add cream, mustard and soy sauce',
      'Mix the sauce with the kotlets and add it to oven for 30-40 mins',
      'Serve with parsley, rice or mashed potatoes',
    ],
  },
  {
    id: '17',
    name: 'Deep fried chicken in sweet chilli sauce',
    category: 'Chicken',
    imageUrl: '/images/shittychicken.jpg',
    ingredients: [
      '400 g of chicken breast fillet or thigh meat',
      '1 egg white',
      '1/2 cup wheat flour',
      '1/4 cup cornstarch',
      '1/2 glass of water',
      '1 tbsp. oil',
      '1/2 tsp. salt',
      '1 l of oil for frying',
      '1 tbsp. of toasted sesame oil',
      '2 cloves of garlic',
      '1 tbsp. rice vinegar',
      '5 tbsp. Sweet Chili Sauce',
      'Sesame seeds For serving',
      'Boiled rice For serving',
    ],

    instructions: [
      'Make the chinese salad first',
      'Cut the chicken into cubes.',
      'Mix egg white, flour, starch, water, 1 tbsp. oil and salt.',
      'Add the chicken pieces to the prepared dough and mix.',
      'Heat the oil in a thick-bottomed pot. You need enough oil to completely submerge the chicken in it. I used 1 liter of oil.',
      'When the oil is hot, we put 1 piece of chicken into it with tongs. We cook in parts so that there is enough space for the chicken in the pot. Bake for about 8 minutes, until the chicken is nicely browned.',
      'Place the cooked chicken on paper towels to absorb excess fat.',
      'When all the chicken is cooked and drained, heat the toasted sesame oil in a pan, grate the garlic and fry for a minute. Add the chicken, rice vinegar and Sweet Chili sauce.',
      'Served with boiled rice, Chinese salad and sprinkled with sesame seeds.',
    ],
  },
  {
    id: '18',
    name: 'Chinese salad',
    category: 'Salad',
    imageUrl: '/images/chineseSalad.jpg',
    ingredients: [
      '3 short cucumbers',
      '1 large carrot',
      '2 cloves of garlic',
      '2 tbsp. soy sauce',
      '1 tbsp. rice vinegar',
      '1 tbsp. toasted sesame oil',
      '1 tbsp. sugar',
      '1 tbsp. sesame seeds',
    ],

    instructions: [
      'Grate the carrots and cucumbers with a large beetroot grater, squeeze the liquid from the cucumbers with your hands. Mix the grated vegetables with the crushed garlic and other ingredients of the sauce. The longer the salad stands, the tastier it becomes, just stir it from time to time.',
    ],
  },
  {
    id: '19',
    name: 'Italian chicken and rice fry',
    category: 'Chicken',
    imageUrl: '/images/italianChicken.jpg',
    ingredients: [
      '500 g of chicken fillet ',
      '1 tbsp. olive oil',
      '1 tbsp. balsamic vinegar',
      '2 cloves of garlic',
      '1/2 tsp. salt',
      '1/2 tsp. ground paprika',
      '1/2 tsp. dried oregano',
      'A pinch of pepper',
      '----------------',
      '2 cloves of garlic',
      '8 sun-dried tomatoes',
      '200 g of rice',
      '300 g of chicken broth',
      '1 tbsp. tomato paste',
      '100 g of tomato puree',
      '100 g of cherry tomatoes',
      '100 g of mozzarella',
      'Parmesan',
      'Pesto sauce',
      'Fresh basil to serve',
    ],

    instructions: [
      'Cut the chicken breast into 1 cm wide slices. Mix them with oil, balsamic vinegar, chopped garlic and all the spices.',
      'Heat the oil in a pan, add the chicken and fry for a few minutes on both sides. Set the fried chicken aside.',
      'Grate the garlic into the pan, add the sun-dried tomatoes cut into large pieces and fry for another minute.',
      'Pour rice into the pan, fry for a minute. Pour broth, tomato paste, tomato puree, mix, return the chicken and cover with a lid and stew over low heat for 12 minutes.',
      'Place cherry tomatoes, pesto sauce, mozzarella pieces on top and sprinkle with parmesan.',
      'Bake in a 200 degree oven for 15 minutes.',
      'Sprinkle with fresh basil before serving.',
    ],
  },
  {
    id: '20',
    name: 'Lazy balandėliai',
    category: 'Chicken',
    imageUrl: '/images/balandeliai.jpg',
    ingredients: [
      '800 g minced chicken or turkey',
      '125 g rice',
      '300 g cabbage',
      '1 large carrot',
      '1 onion',
      '1 egg',
      '1/2 tsp. dried coriander',
      '1/2 tsp. garlic powder',
      'Salt and Pepper',
      'Oil to fry',
    ],
    sauce: [
      '300 ml cream or sour cream',
      '3 tbsp. tomatoe paste',
      '400 ml hot water',
    ],
    instructions: [
      'Boil rice for 10 min, they need to remain firm. Take it out and cool off.',
      'Cut cabbage, onion, carrot and fry them until vegetables soften. Cool them off.',
      'To minced meat add vegetables, rice, egg. Season with spices and mix well',
      'Form meatballs and place them on the oven plate',
      'Combine the ingredients for the sauce and pour it on top. Cook in the oven for 1 hour in 185 degrees.',
      'Serve with mashed potatoes or rice and greenery.',
    ],
  },
  {
    id: '21',
    name: 'Salmon Pokebowl',
    category: 'Fish',
    imageUrl: '/images/pokebowl.jpg',
    ingredients: [
      '1 cup of sushi rice',
      'Handfull of wakame',
      'Handfull of green peas',
      'Half a cucumber',
      '1 avocado',
      'Surimi | Corn',
      '200 g raw salmon',
      '2 tbsp. soy sauce',
      '1 tbsp. sesame oil',
    ],
    sauce: ['2 tbsp. mayonaise', '1 tsp. wasabi'],
    instructions: [
      'Boil rice and let it cool off. Meanwhile cut all the ingredients',
      'Place the rice into a bowl. Add all the ingredients on top of rice',
      'In a separate bowl mix wasabi with mayonaise, add it to the bowl',
      'Serve with soy sauce, sesame oil and sesame seeds',
    ],
  },
  {
    id: '22',
    name: 'Burrito',
    category: 'Beef',
    imageUrl: '/images/burrito.jpg',
    ingredients: [
      '100 g of rice',
      'Oil for frying',
      '500 g of minced beef',
      '2 cloves of garlic',
      '100 g canned black beans',
      '1 package Taco Seasoning Mix',
      '3 tbsp. Taco sauce',
      '150 g of cheddar',
      '1/4 iceberg lettuce',
      '2 tomatoes',
      '8 medium or 6 large tortillas',
      'Jalapeño seasoning (optional)',
    ],

    instructions: [
      'Boil the rice and let it cool while we prepare the other ingredients.',
      'Prepare the meat filling: heat the oil in a pan, add the minced beef and stir-fry for about 7 minutes until the meat is cooked. Grate the garlic and cook for another minute. Add the beans and the spice mixture, mix and cook for another minute. Add the sauce and mix.',
      'Grate the cheese, cut the lettuce into strips, and dice the tomatoes.',
      'Place rice, meat filling, cheese, vegetables in the center of the tortilla and, if desired, add jalapeños.',
      'We roll: we tightly wrap the filling with the lower part of the tortilla, then we fold the sides and roll it into a tight roll. Wrap each burrito tightly in foil.',
      'In this step, you can eat the burritos as they are or heat them in the oven at 180 degrees for 15 minutes and eat them hot. Transfer the remaining burritos to the refrigerator or freezer for later use.',
    ],
  },
  {
    id: '23',
    name: 'Tikka masala in coconut milk',
    category: 'Chicken',
    imageUrl: '/images/tikkamasalacoconut.jpg',
    ingredients: [
      '1 kg chicken tighs',
      '1 can of coconut milk',
      'Garlic cloves',
      'Lemon',
      '1 tbsp. Tikka masala paste',
      'Coriander, rice and fried onions to serve',
    ],

    instructions: [
      'Cut the chicken and fry in the pan until half cooked.',
      'Add the tikka masala paste. Mix and add coconut milk to the pan',
      'Close the pan with the lid and boil for 30 mins.',
      'Squeze some lemon juice.',
      'Add fresh coriander and serve with rice and fried onions',
    ],
  },
  {
    id: '24',
    name: 'Chicken meatballs cream soup',
    category: 'Soup',
    imageUrl: '/images/chickenspinachsoup.jpg',
    ingredients: [
      '400 g minced chicken',
      'Half a cup panko breadcrumbs',
      'Salt and pepper',
      '1 egg',
      'Olive oil to fry',
      '--------------',
      '1.5 tbsp. butter',
      '1 leek',
      '2 carrots',
      '2 tbsp. cream cheese',
      '1.5 l chicken broth',
      '70 g fresh spinach',
      '1 can of white beans',
    ],

    instructions: [
      'Make meatballs out of chicken, egg, salt and pepper and panko breadcrumbs.',
      'Fry from two sides in the pan until golden. Set aside.',
      'In the same pan add butter and fry cut leek and carrots.',
      'Add meatballs back to the pan, add the chicken broth and boil until vegetables soften and the meatballs are cooked',
      'Add the cream cheese, pour spinach and beans and boil until spinach is done.',
    ],
  },
  {
    id: '25',
    name: 'Tomato soup',
    category: 'Soup',
    imageUrl: '/images/pomidoru-sriuba.jpg',
    ingredients: [
      '1 kg. tomatoes',
      '4 large cloves of garlic',
      '1 small onion',
      '1 tbsp. olive oil',
      '1 tbsp. balsamic vinegar',
      '1 tbsp. sugar',
      '1 tbsp. salt',
      '1 tbsp. herbs | Basil, oregano or mixed herbs are fine',
      '1/2 tsp. pepper',
      '2 medium potatoes',
      '1 l vegetable broth',
      'Cheese | For serving',
      'Fresh basil For serving',
    ],

    instructions: [
      'Boil the potatoes',
      'Pour the boiling water to the tomatoes. It will help to peel off the skin.',
      'Place quartered tomatoes, garlic, and onion in a baking pan, sprinkle with sugar, herbs, salt and pepper, sprinkle with olive oil and balsamic vinegar. Bake in a 200 degree oven for about 25 minutes.',
      'Cut the boiled potatoes and add everything from the baking pan to the pot with broth.',
      'Mash the soup. Taste it and, if it is missing, add sugar, salt, and pepper to taste.',
      'Serve sprinkled with grated cheese and fresh basil leaves.',
    ],
  },
  {
    id: '26',
    name: 'Kebabas',
    category: 'Chicken',
    imageUrl: '/images/kebabas.jpg',
    ingredients: [
      'Tortillias',
      'Fermented grated cheese',
      '1 bigger tomatoe',
      '1 cucumber',
      'Lettuce',
      'Marinated red onion',
      '500 g of chciken tighs',
      '2-3 tsp. salt',
      '1 tsp paprika',
      '1 tsp chilli',
      'Oil to fry',
    ],
    sauce: [
      '6 tbsp. greek yoghurt',
      '3 tbsp mayonaise',
      '2 grated garlic cloves',
      '2 tbsp chopped dill',
      '1/2 tsp. coriander',
      'Salt and Pepper to taste',
    ],

    instructions: [
      'Cut the chicken in half, season it and let it stay while preparing other ingredients.',
      'Mix all the sauce ingredients.',
      'Cook the chicken for 4-5 minutes from each side. Before cutting the chicken let it stay for 5 minutes.',
      'Cut the vegetables, grate the cheese.',
      'Put tortillia into the pan, sprinkle with cheese until it melts.',
      'Transfer the tortillia to the plate. Add vegetables, meat, sauce. Roll a kebab, cover the lower end with folium and shove it to the oven for 10 minutes 190 degrees.',
    ],
  },
  {
    id: '27',
    name: 'Sate Chicken',
    category: 'Chicken',
    imageUrl: '/images/satechicken.jpg',
    ingredients: [
      '3-4 chicken breast pieces',
      'Oil to cook',
      '1 onion',
      '3 cloves of garlic',
      'Chopped groundnuts',
      '1 lime',
      'Fresh coriander',
      'Rice to serve',
      '-----------------',
      '1 tbsp. curry',
      '1/2 tsp ground coriander',
      '1/2 tsp ground cumin',
      '1/2 tsp ground turmeric',
      '1/4 tsp chilli pepper',
      '1/2 tsp salt',
      '1/4 tsp pepper',
    ],
    sauce: [
      '2 tbsp nut butter',
      '2 tsp honey',
      '1 tbsp soy sauce',
      '1 tsp rice vinegar',
      '1 tbsp sweet chilli sauce',
      '100 ml coconut milk',
      '50 ml water',
    ],

    instructions: [
      'Prepare the spice mixture - mix all the ingredients.',
      'Cut the chicken into strips and mix with half of the spice mixture. Let it marinate for at least 10 minutes.',
      'We make the sauce: we mix all sauce ingredients in a bowl and the add rest of the spice mix.',
      'Heat oil in a pan, add chopped onion and garlic, fry for a minute.',
      'Add the chicken and cook (try not to overcook).',
      'Pour the sauce, mix and heat on medium heat for 1-2 minutes until the sauce thickens.',
      'Serve with boiled rice and lime wedges. We sprinkle with roasted chopped groundnuts and fresh coriander.',
    ],
  },
  {
    id: '28',
    name: 'Zuchinni pancakes',
    category: 'Pancakes',
    imageUrl: '/images/zuchinnipancakes.jpg',
    ingredients: [
      '2 young zucchini',
      '1 tsp. salt',
      '2 eggs',
      '180 g cottage cheese',
      '2 cloves of garlic',
      'A handful of parsley',
      '100 g of ham',
      '60 g of grated cheese',
      'Salt, pepper',
      '4 tbsp flour',
      'Oil for frying',
    ],
    sauce: [
      '4 tbsp sour cream',
      '1 tsp mayonnaise',
      '1 clove of garlic',
      '1 tsp lemon juice',
      'A pinch of salt, pepper, sugar',
      '1/2 tbsp. dill',
    ],

    instructions: [
      'Grate the zucchini',
      'We mix it with salt and press it with our hands to let the water out, then let it stand for 10 minutes.',
      'Squeeze out the remaining liquid.',
      'We mix grated zucchini with eggs, cottage cheese, chopped parsley, ham, cheese, handful of salt and pepper.',
      'Mix it with flour. You should get a thick mass, if it is too liquid, add a little more flour.',
      'Heat oil in a frying pan and fry slightly larger ones over medium heat for about 10 minuiy, turning occasionally.',
      'For the sauce, mix all the sauce ingredients.',
    ],
  },
];
