export const recipeData = [
  {
    id: '1',
    name: 'Pilaf',
    imageUrl: '/images/plovas.jpg',
    ingredients: [
      '500 g Beef',
      '1 onion',
      '2-3 carrots',
      '1/2 t.s.p. salt',
      '1/4 t.s.p. pepper',
      'Bay leaf',
      '1 t.s.p garlic powder',
      '1 t.s.p paprika',
      '1/2 t.s.p kumin',
      '700 ml beef broth',
      '2 t.s.p tomato paste',
      '350 g rice',
      '1 garlic head',
      'Fresh parsley',
    ],
    instructions: [
      'Cut beef in small cubic pieces.',
      'Cut onion and carrot into small stripes.',
      'Heat the oil in the pan, cook onions for few minutes.',
      'Add carrots, cook for few minutes.',
      'Cook beef but not until it gets roasted.',
      'Mix all the spices and put into the pot.',
      'Add the broth, bay leaf and mix everything.',
      'Cook on low heat for 2-3 hours.',
      'Clean the rice and add to the pot for 20-30 minutes.',
      'Add the cut garlic head.',
      'Serve with fresh parsley.',
    ],
  },
  {
    id: '2',
    name: 'Chicken Noodles',
    imageUrl: '/images/stir-fry.jpg',
    ingredients: [
      '200 g noodles',
      'Oil to fry',
      '400 g of chicken',
      '3 garlic cloves',
      '1 red paprika',
      '200 g beans or brocolli',
      '100 g shiitake mushrooms',
      'sezame seeds',
    ],
    sauce: [
      '4 tbsp soy sauce',
      '2 tbsp oyster sauce',
      '2 tbsp sweet chilli sauce',
      '2 tbsp water',
      '1 tbsp sugar or honey',
      '1 tbsp rice vinegar',
      '1 tbsp sezame oil',
    ],
    instructions: [
      'Cook the noodles as instructed.',
      'Mix everything in a bowl for the sauce.',
      'Preheat the oven and cook the chicken.',
      'Add garlic, ginger and cook for a minute.',
      'Add the cooked noodles and mix it.',
      'Serve with sezame seeds.',
    ],
  },
  {
    id: '3',
    name: 'Creamy Lemon White Fish',
    imageUrl: '/images/creamyFish.webp',
    ingredients: [
      '2 tea spoons butter',
      '2 white fish fillet',
      '250 ml cream (20%)',
      '1 lemon',
      'Salt and pepper',
    ],

    instructions: [
      'Preheat the pan and add butter.',
      'Fry fish from both sides until golden and season with salt and pepper.',
      'Cut half a lemon in slices.',
      'Add cream to the fish.',
      'Add the lemon slices and squeze the remaining half of the lemon.',
      'Cook fish in sauce for 5-10 minutes until cream thickens.',
      'Serve with mashed potatoes or rice.',
    ],
  },
];
