export const recipeData = [
  {
    id: '1',
    name: 'Pilaf',
    imageUrl: '/images/plovas.jpg',
    ingredients: [
      '500 g Beef',
      '1 onion',
      '2-3 carrots',
      '1/2 t.s.p. salt',
      '1/4 t.s.p. pepper',
      'Bay leaf',
      '1 t.s.p garlic powder',
      '1 t.s.p paprika',
      '1/2 t.s.p kumin',
      '700 ml beef broth',
      '2 t.s.p tomato paste',
      '350 g rice',
      '1 garlic head',
      'Fresh parsley',
    ],
    instructions: [
      'Cut beef in small cubic pieces.',
      'Cut onion and carrot into small stripes.',
      'Heat the oil in the pan, cook onions for few minutes.',
      'Add carrots, cook for few minutes.',
      'Cook beef but not until it gets roasted.',
      'Mix all the spices and put into the pot.',
      'Add the broth, bay leaf and mix everything.',
      'Cook on low heat for 2-3 hours.',
      'Clean the rice and add to the pot for 20-30 minutes.',
      'Add the cut garlic head.',
      'Serve with fresh parsley.',
    ],
  },
  {
    id: '2',
    name: 'Chicken Noodles',
    imageUrl: '/images/stir-fry.jpg',
    ingredients: [
      '200 g noodles',
      'Oil to fry',
      '400 g of chicken',
      '3 garlic cloves',
      '1 red paprika',
      '200 g beans or brocolli',
      '100 g shiitake mushrooms',
      'sezame seeds',
    ],
    sauce: [
      '4 tbsp soy sauce',
      '2 tbsp oyster sauce',
      '2 tbsp sweet chilli sauce',
      '2 tbsp water',
      '1 tbsp sugar or honey',
      '1 tbsp rice vinegar',
      '1 tbsp sezame oil',
    ],
    instructions: [
      'Cook the noodles as instructed.',
      'Mix everything in a bowl for the sauce.',
      'Preheat the oven and cook the chicken.',
      'Add garlic, ginger and cook for a minute.',
      'Add the cooked noodles and mix it.',
      'Serve with sezame seeds.',
    ],
  },
  {
    id: '3',
    name: 'Creamy Lemon White Fish',
    imageUrl: '/images/creamyFish.webp',
    ingredients: [
      '2 tea spoons butter',
      '2 white fish fillet',
      '250 ml cream (20%)',
      '1 lemon',
      'Salt and pepper',
    ],

    instructions: [
      'Preheat the pan and add butter.',
      'Fry fish from both sides until golden and season with salt and pepper.',
      'Cut half a lemon in slices.',
      'Add cream to the fish.',
      'Add the lemon slices and squeze the remaining half of the lemon.',
      'Cook fish in sauce for 5-10 minutes until cream thickens.',
      'Serve with mashed potatoes or rice.',
    ],
  },
  {
    id: '4',
    name: 'Pulled Chicken Quesadilla',
    imageUrl: '/images/quesadilla.jpg',
    ingredients: [
      '2 chicken breasts',
      '1 tabl. sp. olive oi',
      'Taco spices pack',
      '2 tabl. sp. salsa sauce',
      '2 tabl. sp. cream cheese',
      '100 g cheddar cheese',
      '6 tortillas',
      'Coriander',
      'Jelapenos',
    ],
    sauce: ['2 Avocados', 'Lime juice', 'Salt and Pepper', '1 tomato'],
    instructions: [
      'Mix the chicken with oil and a mixture of spices.',
      'Fry the chicken: Put the chicken in the pan, fry it on high heat for 3 minutes on each side, then reduce the heat to minimum, cover the pan and fry for another 15 minutes. Let the fried chicken stand at room temperature for 5 minutes, then tear it into thin strips with the help of two forks.',
      'Mix the shredded chicken with salsa sauce and cream cheese.',
      'Grate the cheddar cheese.',
      'Place the chicken filling on the tortilla, add cheese and cover with another tortilla.',
      'Heat oil in a pan and add the tortilla to fry. Fry on medium heat for 3-4 minutes, sometimes pressing the tortilla with your hands or a spatula so that it browns evenly. Carefully turn the tortilla over and cook for another 3-4 minutes. Once cooked, we cut it into 4 or 6 parts.',
      'Prepare guacamole: put avocados in a bowl, squeeze lime juice, grate garlic, add salt and pepper, mash with a fork until smooth. Then we mix in the tomato cubes.',
      'Serve quesadillas with guacamole, lime, chili slices and fresh coriander.',
    ],
  },
  {
    id: '5',
    name: 'Mashed Pumpkin Soup',
    imageUrl: '/images/pumpkinSoup.webp',
    ingredients: [
      '1 pumpkin',
      '2-3 carrots',
      '2 potatoes',
      '1 onion',
      '1 vegetable broth cube',
      '250 ml 7% cream',
      '500 ml water',
      'Pumpkin seads for serving',
      'Grated cheese for serving',
    ],
    instructions: [
      'Peel pumpkin, potatoes carrots and onion. Cut in big pieces',
      'Boil pumpkin, potatoes carrots and onion together in a big pot for 20-25 minutes.',
      'In 500 ml of hot water dissolve vegetable cube. Set aside.',
      'When vegetables are soft, remove the water from the pot, add vegetable broth. Use blender until everything is mashed. Check for salt and add more if necessary',
      'Add 250 ml of cream, mix well. Add freshly ground black pepper',
      'Serve with pumpkin seads and / or grated cheese',
    ],
  },
];
